name: Deploy to Google Play Store

on:
  push:
    branches: [master]
  workflow_dispatch: # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Install EAS CLI
      run: npm install -g eas-cli
      
    - name: Setup Expo CLI
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Create Google Service Account Key
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > google-service-account.json
        
    - name: Build Android App Bundle
      run: eas build --platform android --profile production --non-interactive --wait
      
    - name: Submit to Google Play Store
      run: eas submit --platform android --latest --non-interactive
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        
    - name: Clean up
      run: rm -f google-service-account.json 