name: Deploy to Google Play Store (with Version Management)

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update version and version code
      run: node scripts/update-version.js
      
    - name: Commit version changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app.json
        git commit -m "Auto-increment version for deployment" || echo "No changes to commit"
        git push
        
    - name: Setup Expo CLI
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Create Google Service Account Key
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > google-service-account.json
        
    - name: Build Android App Bundle
      run: eas build --platform android --profile production --non-interactive --wait
      
    - name: Submit to Google Play Store
      run: eas submit --platform android --latest --non-interactive
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        
    - name: Clean up
      run: rm -f google-service-account.json
      
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Deployment completed successfully!"
        echo "App has been submitted to Google Play Store"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "Please check the logs for more details" 